name: SAST

on:
  push:
    branches: [ main, dev/* ]
  pull_request:
    branches: [ main, dev/* ]

jobs:
  codesniffer-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer run action PHPC_CS
        uses: MayMeowHQ/composer-run-action@v7
        with:
          composer_script: 'cs-check'

  stan-admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer run action PHPStan
        uses: MayMeowHQ/composer-run-action@v7
        with:
          composer_script: 'stan'
          memory_limit: '2048M'
